### ISSUE TITLE
Error thrown while closing WSC dialog

### ISSUE THREAD

**Issue by oleq** [WebSpellChecker/ckeditor-plugin-wsc#32]
[A bug](http://dev.ckeditor.com/ticket/13925) on CKEditor tracker.

---

## Steps to reproduce

1. Open samples/index.html (also http://ckeditor.com/demo)
1. Set the following data
 ```
<p>asd</p>
<p>zxc</p>
<p>qwe</p>
<p>asd</p>
```
1. From the SCAYT dropdown select "Enable SCAYT".
1. From the SCAYT dropdown select "Check Spelling".
1. Click "Change to".
1. Click "Change to".
1. Click "Finish Checking".

## Expected result

Dialog closes. Back to editing content.

## Actual result

Error in the console

```getWordsInfockscayt.js:36:10529 TypeError: g.ltr is not an Object. (evaluating 'c in g.ltr')```

Dialog does not close, just keeps displaying a spinner.

## Other details (browser, OS, CKEditor version, installed plugins)

WSC Version: 3.0.7670

Tested in Chrome Version 46.0.2490.86 (64-bit), Safari Version 9.0.1 (11601.2.7.2)

**Comment by WebSpellChecker** [comment]
Hi Oleq,

Issue is already fixed in scayt-dev. Fix will be pushed to master branch after WebSpellChecker.net release 4.8.2. Also, approximately, this fix will be inlcuded in CKEditor defaul package in v 4.5.6.

For now, to avoid the issue you could rebuild CKEditor with new SCAYT plugin from scayt-dev branch. 
Please find the manual below:

Clone the CKEditor development repository hosted at GitHub:

git clone https://github.com/ckeditor/ckeditor-dev.git
Switch to the version that you need:

git checkout tags/your_version

Go to /plugins folder and clone SCAYT:

git clone https://github.com/WebSpellChecker/ckeditor-plugin-scayt.git -b scayt-dev scayt

Update config.js and dev/builder/build-config.js files with SCAYT plugin to include it into the CKEditor configuration:

'scayt,' +
and
'scayt: 1'

Build CKEditor:

sh build.sh

Built CKEditor with updated SCAYT plugin is located in the 'release' folder

**Comment by oleq** [comment]
We'll stick to the stable SCAYT in CKEditor 4.5.5 because we're very close to the release anyway. But it's good to know that you keep an eye on this issue. Thanks!

**Comment by oleq** [comment]
It looks like the issue is fixed. Shouldn't it be included in https://github.com/WebSpellChecker/ckeditor-plugin-scayt/blob/605956c1ccaacf0a162fbcd12d5b6f78d126952b/CHANGELOG.md changeset?

**Comment by WebSpellChecker** [comment]
Included with comment "fixed: SCAYT stops working after pressing Cancel button in WSC dialog"

**Comment by oleq** [comment]
Thanks!
